version: "3"
services:
  backend:
    build:
      dockerfile: etc/docker/php/Dockerfile
      context: .
    environment:
      PHP_IDE_CONFIG: "serverName=cli.dev.website"
    networks:
      - app_net
    volumes:
      - .:/app
    ports:
      - "80:8000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_USER: user
    networks:
      - app_net
    ports:
      - "5432:5432"

networks:
  app_net: